ALTER TABLE public.projects
  ADD COLUMN IF NOT EXISTS doc_url TEXT NULL,
  ADD COLUMN IF NOT EXISTS problem TEXT NULL,
  ADD COLUMN IF NOT EXISTS solution TEXT NULL,
  ADD COLUMN IF NOT EXISTS impact TEXT NULL;